version: "3.9"
   
services:
    front:
      build: 
        context: ./front
        dockerfile: Dockerfile
      ports:
        - 4201:4200
      depends_on: 
        - api
    api: 
      build:
        context: ./api
        dockerfile: Dockerfile
      ports: 
        - 4000:4000
      depends_on:
          - db
    db:
      build:
        context: ./database
        dockerfile: Dockerfile
      ports:
        - 5434:5432