version: "3.9"
   
services:
    api2: 
      build:
        context: ./api
        dockerfile: Dockerfile
      ports: 
        - 4002:4000
      depends_on:
          - db2
    db2:
      build:
        context: ./database
        dockerfile: Dockerfile
      ports:
        - 5434:5432